---
dmci:
  distributors:
    - file
    - pycsw
  distributor_cache: /workdir
  max_permitted_size: 100000
  mmd_xsl_path: /usr/share/mmd/xslt/mmd-to-geonorge.xsl
  mmd_xsd_path: /usr/share/mmd/xsd/mmd_strict.xsd

pycsw:
  csw_service_url: http://localhost

customization:
  catalog_url: http://localhost
  env_string: dev

file:
  file_archive_path: /workdir
