dmci:
  distributors:
    - file
    - pycsw
  distributor_cache: null
  max_permitted_size: 100000
  mmd_xslt_path: null
  mmd_xsd_path: null

pycsw:
  csw_service_url: localhost

file:
  file_jobs_path: null
