dmci:
  distributors:
    - file
    - pycsw
    - solr
  distributor_cache: null
  rejected_jobs_path: null
  max_permitted_size: 100000
  mmd_xsl_path: null
  mmd_xsd_path: null
  path_to_parent_list: null

pycsw:
  csw_service_url: http://localhost

customization:
  catalog_url: http://localhost
  env_string: null

file:
  file_archive_path: null

solr:
  solr_service_url: http://localhost:8983/solr/senda
  solr_username: null
  solr_password: null
