dmci:
  distributors:
    - file
    - pycsw
  distributor_cache: null
  rejected_jobs_path: null
  max_permitted_size: 100000
  mmd_xslt_path: null
  mmd_xsd_path: null
  path_to_parent_list: null

pycsw:
  csw_service_url: http://localhost

file:
  file_archive_path: null
