name: pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pyTestCov:
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11']
    runs-on: ubuntu-latest
    steps:
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-timeout
          pip install pytest-cov
      - name: Run Tests
        run: python -m pytest -v --cov=dmci --timeout=60
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
